appName: osiris-ingress

deployment:
  annotations:
    sidecar.jaegertracing.io/inject: "true"

  replicas: 1
  image:
    repository: <IMAGENAME>
    tag: latest
  livenessProbe:
    path: /
    initialDelaySeconds: 15
    timeoutSeconds: 2
    periodSeconds: 60
  readinessProbe:
    path: /
    initialDelaySeconds: 15
    timeoutSeconds: 2

service:
  type: ClusterIP
  annotations:
   prometheus.io/scrape: "true"
   # prometheus.io/path: /metrics
   # prometheus.io/port: 9102

ingress:
  enabled: false
  host: 
  path: /
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx

config:
  conf.ini: |
    [Logging]
    configuration_file = <configuration_file>.conf

    [FastAPI]
    root_path = <root_path>

    [Azure Storage]
    account_url = https://<storage_name>.dfs.core.windows.net/
    filesystem_name = <container_name>
  log.conf: |
    [loggers]
    keys=root,main

    [handlers]
    keys=consoleHandler,fileHandler

    [formatters]
    keys=fileFormatter,consoleFormatter

    [logger_root]
    level=DEBUG
    handlers=consoleHandler

    [logger_main]
    level=INFO
    handlers=consoleHandler
    qualname=main
    propagate=0

    [handler_consoleHandler]
    class=StreamHandler
    formatter=consoleFormatter
    args=(sys.stdout,)

    [handler_fileHandler]
    class=FileHandler
    formatter=fileFormatter
    args=('logfile.log',)

    [formatter_fileFormatter]
    format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
    datefmt=

    [formatter_consoleFormatter]
    format=%(levelname)s: %(name)s - %(message)s
