---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
    app.kubernetes.io/name: {{ .Values.appName }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Values.appName }}
    app.kubernetes.io/component: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version }}
  name: {{ .Values.appName }}
  annotations:
  {{- range $key, $value := .Values.deployment.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        name: {{ .Values.appName }}
        ports:
        - containerPort: 80
          name: deploy-port
        volumeMounts:
        - name: config-volume
          mountPath: /etc/osiris/
        livenessProbe:
          httpGet:
            path: {{ .Values.deployment.livenessProbe.path }}
            port: 80
          initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.deployment.readinessProbe.path }}
            port: 80
          initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.appName }}-cm
      
