{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http: 
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ .Values.appName }}-svc
          servicePort: 80
{{- end -}}