---
apiVersion: v1
kind: Service
metadata:
  annotations:
      prometheus.io/scrape: "true"
  name: {{ .Values.appName }}-svc
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: deploy-port
  type: {{ .Values.service.type }}
