---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: deploy-port
  type: {{ .Values.service.type }}